// English locale dictionary for DSH Dock (4.13 i18n).
import type { AppCopy } from "./zh-CN"

export const enUS: AppCopy = {
  boot: {
    progressLabel: "Starting up",
    steps: [
      { no: "01", name: "Environment Check", hint: "Making sure your computer is ready to run DSH" },
      { no: "02", name: "Prepare Engine", hint: "Getting DSH components ready (first run downloads them)" },
      { no: "03", name: "Launch Workbench", hint: "Starting the DSH service" },
      { no: "04", name: "Awaiting Ready", hint: "Almost there — first launch can take a moment" },
      { no: "05", name: "Enter Workbench", hint: "Opening the workbench for you" },
    ],
    headlines: [
      "Checking Runtime Engine",
      "Preparing Runtime Environment",
      "Launching Workbench",
      "Waiting for Service Ready",
      "Entering Workbench Soon",
    ],
    stRunning: "Running",
    copyDetail: "Copy details",
    copied: "Copied",
    progressAria: "Startup progress: {done} of {total}",
    dlPackages: "{done} / {total} packages",
    wslOpen: "Open in WSL",
    wslOpenTip: "Run DSH inside WSL2 distro (requires Windows + WSL2)",
    wslFailed: "Failed to switch to WSL",
    localOpen: "Open Locally",
    localOpenTip: "Switch back to local mode",
    localFailed: "Failed to switch to local",
    controlCenter: "Control Center",
    controlCenterTip: "Open Control Center (manage profiles, plugins, credentials, diagnostics)",
    launchingTitle: "Launching Workbench...",
    launchingSub: "Connecting to local service and runtime, entering workbench soon",
    viewTimeline: "View startup details",
    hideTimeline: "Hide details",
  },
  handoff: {
    titleStart: (name: string) => `Starting "${name}"`,
    titleRestart: (name: string) => `Restarting "${name}"`,
    titleSwitch: (name: string) => `Switching to "${name}"`,
    stageStopping: "Stopping session",
    stageBooting: "Starting session",
    stageWaiting: "Waiting for ready",
    stageEntering: "Entering workbench",
    phaseStopping: "Stopping the current session…",
    phaseBooting: "Preparing and starting the new session…",
    phaseWaiting: "Service started, waiting until it is ready…",
    phaseEntering: "Ready — opening the workbench…",
    phaseReady: "Workbench is ready",
    phaseFailed: "Launch interrupted — see the error card in the main window",
    elapsedTitle: "Elapsed time for this operation (continuous across windows)",
    focusWorkbench: "View progress",
    enterWorkbench: "Open workbench",
    viewFailure: "View error details",
    dismissFailure: "Dismiss this failure notice",
  },
  error: {
    fallbackTitle: "Launch Failed",
    actionFailed: "Action Failed",
    // Clipboard write failure (2026-09-08, batch 0b): never fake a "copied" state
    copyFailed: "Copy failed — please select the text and copy manually",
    actions: {
      retry: "Retry",
      upgrade: "Upgrade DSH & Retry",
      upgrade_only: "Upgrade in Background",
      reselect: "Reselect",
    } as Record<string, string>,
    // Error-card static labels (2026-09-08, ADR-0012)
    diagHeader: "DIAG Console",
    cardHeader: "Launch Interrupted",
    suggestionLabel: "Suggested fix:",
    // Per-kind copy (ADR-0012): looked up by failure.kind, falling back to the
    // backend-provided title/suggestion when the kind is unknown.
    kinds: {
      credentials_mismatch: {
        title: "Your DSH host does not match your credential format",
        suggestion:
          "This usually means DSH is too old: upgrading to the latest official release fixes it (the upgrade only touches the global pnpm/npm, never your data).",
      },
      incompatible_options: {
        title: "DSH host options are incompatible",
        suggestion: "Upgrade your DSH to a version that supports the current terminal behavior.",
      },
      network_unavailable: {
        title: "Network unavailable",
        suggestion: "Live downloads need a network connection; check your network and retry.",
      },
      unknown: {
        title: "DSH workbench failed to start",
        suggestion: "See the log for details; retry, and report it if it keeps happening.",
      },
    } as Record<string, { title: string; suggestion: string }>,
  },
  mode: {
    title: "Select Runtime Environment",
    subline: "DSH can run locally or inside a WSL2 distro — switchable anytime from menu",
    local: "Run Locally",
    localDesc: "Powered by managed runtime engine; automatically bootstraps Node and DSH on first run, then runs completely offline",
    wsl: "Run in WSL2",
    wslDesc: "Launch DSH inside WSL2 distro (requires Windows + WSL2; engine automatically staged inside distro)",
    setDefault: "Set as default launch mode (used automatically next time)",
    next: "Start",
    starting: "Switching…",
    failed: "Environment switch failed",
  },
  selector: {
    title: "Select Workbench",
    subtitle: "Multiple webUi workbenches available. Choose one to start.",
    headline: "Which workbench would you like to enter?",
    subline: "From your local DSH environment · Affects this session only",
    pickHint: "Official Web workbench works out of the box; others are customized webUi workspaces.",
    launchingPrefix: "Launching \"",
    launchingSuffix: "\"",
    preparingTitle: "Preparing Engine Runtime",
    preparingSub: "Bootstrapping Node & DSH runtime for first launch · One-time setup",
    problemHeadline: "Startup Encountered an Issue",
    items: {
      web: { title: "Official Web Workbench", desc: "Official Web interface maintained by DSH", tag: "DEFAULT" },
    } as Record<string, { title: string; desc: string; tag: string }>,
    customDesc: "Custom assembled webUi workbench",
    customTag: "CUSTOM",
    chipDshNew: "Update Available",
    chipDshOk: "Up to Date",
    chipDetecting: "Detecting",
    chipCheckFailed: "Check Failed",
    chipClientNew: "App Update Available",
    chipClientUpdating: "Updating App",
    chipClientUpdatingRun: "Updating App…",
    // Workbench Launchpad
    rememberChoice: "Remember my choice and enter this workbench directly next time",
    quickKeysHint: "Press keys 1-9 to quickly launch",
    createWorkbench: "Create New Workbench",
    createWorkbenchDesc: "Clone templates or customize workspaces in Control Center",
    manageWorkbenches: "Workbench Manager",
    engineReady: "Engine Ready",
    pluginsCount: "{count} plugins",
    defaultBadge: "DEFAULT",
    enterWorkbench: "Open Workbench",
    launching: "Starting…",
  },
  updateBanner: {
    dshTitle: "dsh v{latest} available (current v{current})",
    dshConsequence:
      "Upgrading brings security fixes and improvements; staying behind may block future upgrades when version requirements rise.",
    clientTitle: "App v{latest} available",
    clientConsequence: "Upgrade is recommended for fixes and improvements.",
    dismissTip: "Dismiss this version",
    entryHint: "Open the update center from the About entry in the menu / tray.",
  },
  about: {
    workbenchLabel: "Workbench instances",
    title: "About & Updates",
    tagline: "Update Center · Desktop Client & Runtime",
    clientLabel: "Desktop Client",
    phases: {
      idle: "Idle",
      checking: "Checking",
      available: "Available",
      upToDate: "Up to Date",
      downloading: "Downloading",
      installing: "Installing",
      relaunching: "Relaunching",
      done: "Done",
      failed: "Failed",
    },
    lines: {
      idle: "Click \"Check for Updates\" to query official releases",
      checking: "Checking official release source",
      upToDate: "Already up to date",
      downloading: "Downloading new version",
      installing: "Installing update",
      relaunching: "Relaunching into new version",
      failedTitle: "Update Failed",
    },
    foundNew: "New Version Found",
    releaseNotes: "Release Notes",
    downloadBtn: "Download & Install",
    preparing: "Preparing installation…",
    checkBtn: "Check for Updates",
    updatedDone: "Updated to",
    restartNote: "Client updates are signed by official Releases and restart automatically after install.",
    envTitle: "Runtime Environment",
    dshLabel: "DSH",
    nodeLabel: "Node Runtime",
    notDetected: "Not Detected",
    detecting: "Detecting…",
    hasNew: "Update Available",
    latestIsNewest: "Up to Date",
    latestOfficial: "Official Latest",
    notYetLocal: "Not yet detected locally",
    checkFailedNet: "DSH Check Failed (Network Unreachable)",
    nodeFromEngine: "Shell engine · managed by the app",
    nodeFromSystem: "From your system",
    nodeManaged: "Managed by App · Automatically prepared",
    nodeUnknown: "Unknown",
    dshUpgradeNote: "Upgrading DSH only updates global pnpm/npm packages and does not touch your data or configurations.",
    upgrading: "Upgrading…",
    upgradeFailed: "Upgrade Failed",
    upgradeRunning: "Installing globally via pnpm/npm, this may take several minutes…",
    btnCheck: "Check",
    btnUpgrade: "Upgrade",
    // Version picker (2026-09-09): "new version" only reflects the upgradable
    // line (stable/rc); preview builds are opt-in via the version list.
    btnUpgradeTo: "Upgrade to",
    installingVersion: "Installing",
    previewReleased: "Preview released:",
    previewView: "View",
    versionListEntry: "All versions",
    noteUpgraded: "Upgraded to",
    noteAlreadyLatest: "Already latest",
    onPreview: "Preview build · stable line",
    versionListTitle: "DSH Versions",
    versionListHint: "Preview builds may be unstable — you can roll back anytime.",
    filterAll: "All",
    filterUpgradable: "Stable · RC",
    filterPreview: "Preview",
    channelStable: "Stable",
    channelRc: "RC",
    channelAlpha: "Preview",
    channelOther: "Preview",
    rowInstall: "Install",
    rowRollback: "Roll back",
    rowCurrent: "Current",
    listLoadFailed: "Failed to load versions",
    listRetry: "Retry",
    listEmpty: "No versions match this filter",
    cancelBtn: "Cancel",
    confirmAlphaTitle: "Install Preview Build",
    confirmAlphaNote:
      "is a preview build — it may be unstable, or its dependencies may not be fully published.",
    confirmAlphaPoints: [
      "Preview builds are for early adoption and feedback; not recommended for production use",
      "If something breaks, roll back to a stable version from the version list anytime",
    ],
    confirmRollbackTitle: "Roll Back to Older Version",
    confirmRollbackNote:
      "is older than the installed version — rolling back reinstalls the global dsh package.",
    confirmRollbackPoints: [
      "Rolling back only reinstalls the global dsh package; your data and configuration are not affected",
      "Sessions created on a newer version may not open on an older one",
    ],
    confirmInstallAnyway: "Install Anyway",
    confirmRollbackOk: "Roll Back",
    openInBrowser: "Open in Browser",
    workbenchNotReady: "Workbench not ready yet",
    liveSessionActive: "Workbench Session Active",
    copyDiagnostics: "Copy Diagnostics",
    diagnosticsCopied: "Diagnostics copied to clipboard",
    officialChannel: "Official Release Channel",
  },
  profiles: {
    moreActions: "More actions",
    listLabel: "Profile list",
    detailWorkspaceLabel: "Profile detail workspace",
    distributeTargetLabel: "Select target profile",
    distributeWithConfig: "Copy config lines too",
    mcpDisable: "Disable this MCP server",
    mcpEnvRemove: "Remove this environment variable",
    title: "Control Center",
    subtitle: "Workspaces management, plugin matrix, session self-healing, and system console",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    refreshData: "Refresh Data",
    dataRefreshed: "Profile and plugin data refreshed",
    reloadingWorkbench: "Reloading workbench…",
    launchingProfile: "Starting service…",
    switchToDsh: "Return to DSH",
    switchToDshTip: "Quick switch back to DSH Workbench (Shortcut: ⌘ + , / Ctrl + , to toggle)",
    createBtn: "New Profile",
    loadFailed: "Failed to read profiles. Please verify DSH environment and retry.",
    retryLoad: "Retry",
    tagMaterialized: "Created",
    tagTemplate: "Template",
    tagNoUi: "Headless",
    templateHint: "Built-in template · Materialized automatically on first launch",
    defaultBadge: "Default",
    runningBadge: "Running",
    setDefault: "Set as Default",
    defaultIs: "Current Default",
    launch: "Launch",
    launchWorking: "Launching…",
    metaBundles: (n: number) => `${n} plugins`,
    metaDeps: (n: number) => (n > 0 ? `${n} dependencies` : "No extra dependencies"),
    metaSep: "·",
    detailTitle: (name: string) => `Details: "${name}"`,
    detailPackage: "Package Name",
    detailBundles: "Plugin Bundles (dsh.profile.bundles)",
    detailDeps: "Plugins (dependencies)",
    detailPatch: "cordis.patch.yml Content",
    detailPatchNone: "No patch layer yet (generated by DSH on first run)",
    detailEmptyDeps: "No extra dependencies",
    detailClose: "Close",
    pluginNotInstalled: "Not Installed",
    pluginInstallBtn: "Install Plugin",
    pluginInstallPlaceholder: "Package name or pkg@version (e.g. dsh-xxx@^1.2)",
    pluginInstallSubmit: "Install",
    pluginInstallCancel: "Cancel",
    pluginInstallBusy: "Installing… (Downloading may take up to minutes)",
    pluginUninstall: "Uninstall",
    pluginUninstallConfirm: (pkg: string) => `Uninstall plugin "${pkg}"?`,
    pluginUninstallPoints: [
      "Runs dsh plugin remove, dropping it from this profile's dependencies",
      "The plugin's own config files are not deleted by this action",
      "If the profile is running, this takes effect after a restart; reinstalling is required to use it again",
    ],
    pluginUpdate: "Update",
    pluginDisable: "Disable (Requires Restart)",
    pluginEnable: "Enable (Requires Restart)",
    pluginDisabled: "Disabled",
    pluginOpBusyRemove: "Uninstalling…",
    pluginOpBusyUpdate: "Updating…",
    checkUpdatesBtn: "Check Updates",
    updateCheckStarted: "Update check started — see menu badge & About",
    checkingBtn: "Checking…",
    updateChecked: (r: { checked: number; failed: number }) =>
      `Checked ${r.checked} plugins${r.failed ? ` · ${r.failed} failed` : ""}`,
    allUpToDate: "All up to date",
    updateHint: "Select version to update",
    pickVersionTitle: (pkg: string) => `Available versions for "${pkg}"`,
    versionLatest: "Latest",
    versionCurrent: "Current",
    versionsLoadFailed: "Failed to query versions",
    hiddenLayersHint: (n: number) => `There are ${n} additional plugin layers below`,
    pluginWithDsh: "Version follows DSH",
    runtimeSummary: (s: { active: number; failed: number; loading: number; disabled: number }) =>
      `Session active · ${s.active} active${s.failed ? ` · ${s.failed} failed` : ""}${s.loading ? ` · ${s.loading} loading` : ""}${s.disabled ? ` · ${s.disabled} disabled` : ""}`,
    runtimeUnavailable: "Profile is not currently running; showing static manifest",
    createTitle: "Create Profile",
    createNameLabel: "Profile Name",
    createNamePlaceholder: "e.g. my-workbench",
    createNameHelp: "Creating with same name retries installation (idempotent); existing complete names are rejected",
    createTemplateHint: (name: string) =>
      `"${name}" is a built-in template: will be initialized as official ${name === "web" ? "Web" : "Headless"} workbench`,
    createDefaultHint: "Will create Base + Web workbench (same structure as official web template, zero download), ready to launch or set as default",
    createSubmit: "Create",
    createBusy: "Creating… (Local setup, usually takes seconds)",
    createDoneReady: "Created: Base + Web workbench is ready to launch or set as default",
    createDonePending: "Created, but plugin installation is still pending — you can retry creation later",
    createDoneFailed: "Creation incomplete",
    createAgain: "Try Again",
    copyTitle: (name: string) => `Duplicate "${name}"`,
    renameTitle: (name: string) => `Rename "${name}"`,
    newNameLabel: "New Name",
    copyNote: "Duplication excludes node_modules (reinstalled by pnpm in new folder); all other files are copied as-is",
    renameNote: "node_modules will be cleaned up on rename and auto-repaired on next DSH launch",
    submitCopy: "Create Copy",
    submitRename: "Confirm Rename",
    actionRename: "Rename",
    actionDelete: "Delete",
    busyShort: "Processing…",
    renameSame: "New name is identical to current name",
    nameOccupied: "This name is already occupied",
    renameDone: (name: string) => `Renamed to "${name}"`,
    copyDone: (name: string) => `Created copy "${name}"`,
    warningsLabel: "Manual check recommended",
    opFailed: "Operation Failed",
    deleteTitle: (name: string) => `Delete "${name}"?`,
    deleteNote: "This action cannot be undone",
    deletePoint: [
      "Only this profile directory will be removed; global sessions and credentials remain untouched",
      "Ensure no other DSH processes are currently using this profile",
      "If this is a template name (web/headless), it will re-materialize on next launch",
    ] as readonly string[],
    deleteConfirm: (name: string) => `Confirm Delete ${name}`,
    deleteBusy: "Deleting…",
    deleteDoneCleared: "Deleted; was default profile, reverted to web",
    deleteDone: "Deleted",
    setDefaultDone: (name: string) => `Set "${name}" as default launch profile`,
    switchTitle: (name: string) => `Switch to "${name}"?`,
    switchNote: "Will stop current DSH instance and restart with target profile. Ongoing tasks will pause (session history preserved); default profile setting remains unchanged.",
    switchFrom: (active: string) => `Currently running: "${active}"`,
    switchConfirm: (name: string) => `Switch to "${name}"`,
    switchBusy: "Switching…",
    switchDone: (name: string) => `Switching to "${name}", see main window for progress`,
    restart: "Restart",
    restartTitle: (name: string) => `Restart "${name}"?`,
    restartNote: "Will stop current DSH instance and restart with same profile. Newly installed/uninstalled/disabled plugins will take effect.",
    restartConfirm: (name: string) => `Restart "${name}"`,
    restartBusy: "Restarting…",
    restartDone: (name: string) => `Restarting "${name}", see main window for progress`,
    viewProfiles: "Profiles",
    viewPluginHub: "Plugin Hub",
    viewPlugins: "Installed Plugins",
    viewMarket: "Marketplace",
    viewSessions: "Sessions",
    viewConsole: "Console",
    overviewSubtitle: "Third-party plugin distribution across all profiles",
    overviewSourceCount: (n: number) => `${n} profiles`,
    overviewEmpty: "No third-party plugins installed yet",
    overviewEmptyHint: "Plugins will be summarized here once installed in any profile",
    overviewNotInstalled: "Not Installed",
    importBtn: "Import from Other",
    importBtnTitle: "Install plugins from other profiles here",
    importTitle: (name: string) => `Import plugins into "${name}"`,
    importNote: "Installs same version by default; \"With Config\" copies patch entries verbatim (does not overwrite existing)",
    importLoading: "Scanning other profiles…",
    importEmpty: "No third-party plugins in other profiles",
    importRowsFailedNote: "Failed to query some plugin rows; \"With Config\" availability may be imprecise",
    importConfig: "With Config",
    importNoConfig: "No config to carry",
    importSelected: (n: number) => `Selected ${n}`,
    importStart: (n: number) => `Install ${n} items`,
    importRunning: (i: number, total: number) => `Installing ${i}/${total}`,
    importDone: (ok: number, fail: number) =>
      `Import complete: ${ok} succeeded${fail ? ` · ${fail} failed` : ""}`,
    importDoneBtn: "Done",
    importFailures: "Failure Details",
    searchPlaceholder: "Search profiles...",
    searchPluginsPlaceholder: "Search installed plugins...",
    searchAllPluginsPlaceholder: "Search plugins across all profiles...",
    tabPlugins: "Plugins",
    tabBundles: "Base Bundles",
    tabPatch: "Patch YAML",
    tabMcp: "MCP Extensions",
    mcpTitle: "MCP Server Manager",
    mcpSubtitle: "Manage Model Context Protocol external tools and services for this profile",
    mcpEmpty: "No MCP servers configured in this profile yet",
    mcpAddBtn: "Add MCP Server",
    mcpLoadFailed: "Failed to load MCP configuration",
    mcpRetry: "Retry",
    mcpEditBtn: "Edit",
    mcpDeleteBtn: "Delete",
    mcpDeleteConfirm: (name: string) => `Remove MCP server "${name}"?`,
    mcpDeleteNote: "This will be safely removed from cordis.patch.yml.",
    mcpActiveTools: (count: number) => `${count} tools active in runtime`,
    mcpNoActiveTools: "Not running or no exported tools",
    mcpModalTitle: "Configure MCP Server",
    mcpModalDesc: "Configure server name, command, arguments, and environment variables. Synced atomically to cordis.patch.yml.",
    mcpPresetTitle: "Quick Apply Preset",
    mcpServerName: "Server Name",
    mcpCommand: "Command",
    mcpArgs: "Arguments (Args)",
    mcpEnv: "Environment Variables (KEY=VALUE per line)",
    mcpPrefix: "Tool Prefix",
    mcpSaveBtn: "Save Server",
    mcpSaveSuccess: (name: string) => `MCP server "${name}" saved to cordis.patch.yml`,
    mcpDeleteSuccess: "MCP server removed successfully",
    mcpConfigSaved: "MCP configuration synced to cordis.patch.yml",
    emptySelectTitle: "No Profile Selected",
    emptySelectSubtitle: "Select a profile from the left or create a new workbench to manage plugins, base bundles, and YAML patch.",
    quickDistribute: "Distribute to...",
    distributeTitle: (pkg: string) => `Distribute "${pkg}" to other profiles`,
    distributeNote: "Select target profile to install same version and optionally migrate configuration",
    distributeDone: (pkg: string, target: string) => `Successfully installed "${pkg}" into "${target}"`,
    distributeConfigFailed: (pkg: string, target: string, reason: string) =>
      `"${pkg}" was installed into "${target}", but configuration migration failed: ${reason}`,
    distributeConfigSkipped: (pkg: string, target: string) =>
      `"${pkg}" was installed into "${target}"; target already had matching config lines, left untouched`,
    copyPatchSuccess: "Patch YAML copied to clipboard",
    rawYamlHint: "Authoritative cordis.patch.yml generated by DSH (read-only diagnostics)",
    filterAll: "All",
    filterMaterialized: "Created",
    filterTemplates: "Templates",
  },
  sessions: {
    title: "Session Maintenance & Self-Healing",
    subtitle: "Inspect, diagnose, and auto-repair DSH session log anomalies (sequence gaps, concurrent writes, etc.)",
    scanBtn: "Refresh Sessions",
    repairAllBtn: "Run Full Health Check & Repair",
    repairing: "Repairing in progress…",
    searchPlaceholder: "Search by session name, ID or project...",
    filterAll: "All Sessions",
    filterNeedsRepair: "Needs Repair Only",
    filterArchived: "Archived",
    groupByProject: "Group by Project",
    allProjects: "All Projects",
    workspacePath: "Workspace Path",
    openInFinder: "Open in File Explorer",
    totalCount: (n: number) => `Found ${n} sessions`,
    healthyCount: (n: number) => `${n} healthy`,
    needsRepairCount: (n: number) => `${n} need repair`,
    repairBtn: "Repair",
    repairAllDisabled: "Only unhealthy sessions need repair",
    noTitle: "Untitled Session",
    statusHealthy: "Healthy",
    statusNeedsRepair: "Needs Repair",
    statusUnknown: "Unknown",
    statusRunning: "Running",
    statusRunningDesc: "Session is in use by dsh; safe to repair after it ends",
    statusHealthyDesc: "Session log sequence intact, ready to open",
    statusNeedsRepairDesc:
      "Repairable anomaly detected (replay overlap, sequence gap, generation divergence); repair to view the full session",
    statusUnknownDesc: "Cannot determine health (possibly active session or engine not ready)",
    statusUnknownDescWithReason:
      "Health state cannot be determined automatically — the reason from the repair script is shown below",
    repairNeedHint: "Only unhealthy sessions can be repaired",
    backupTag: "Backed Up",
    // Archive & metadata (2026-09-07): archive semantics aligned with dsh sidebar
    // (hidden by default); metadata fields are informational only.
    archivedTag: "Archived",
    archivedTagDesc: "Archived in dsh (hidden by default; view & repair here)",
    subagentTag: "Subagent",
    subagentTagDesc: "Subagent session (delegated by another session)",
    endStateStop: "Ended",
    endStateInterrupted: "Turn Interrupted",
    endStateAborted: "Aborted",
    endStateError: "Ended with Error",
    endStateOpen: "Unclosed",
    eventCountTitle: "Total expanded events",
    agentPresetTitle: "Agent preset",
    createdAtTitle: "Created",
    validatorHint: (v: string) => ` (validator: ${v})`,
    compressedTag: "Zstd Compressed",
    plainTag: "Plaintext",
    repairSuccess: (id: string) => `Session "${id}" successfully repaired`,
    repairAllSuccess: "All sessions scanned and repaired!",
    emptyList: "No session records found",
    emptyFilter: "No matching sessions",
    lastUpdated: "Last Active",
    fileSize: "Size",
    path: "Storage Path",
    deleteBtn: "Delete",
    deleteConfirmTitle: (id: string) => `Delete session "${id}"?`,
    deleteConfirmNote: "This will permanently remove the session log file and its local history. This cannot be undone.",
    deleteSuccess: "Session record successfully deleted",
    copyPath: "Copy Path",
    pathCopied: "Session path copied",
  },
  console: {
    toastClose: "Dismiss notification",
    navLabel: "System console navigation",
    detailLabel: "System console detail area",
    pullLatestLogs: "Refresh logs",
    rereadCredentials: "Refresh credentials",
    title: "System Console & Diagnostics",
    subtitle: "Preferences, LLM credentials, DSH engine settings, auto-recovery guardian, telemetry, and live logs",
    tabPreferences: "Preferences & Guardian",
    tabCredentials: "Model Credentials",
    tabDshSettings: "DSH Engine Settings",
    tabDiagnostics: "Health Telemetry",
    tabLogs: "Live Logs",
    // 凭据安全管理（4.5）
    credentialsTitle: "LLM & Service Credentials",
    credentialsSubtitle: "Securely manage $DSH_HOME/.credentials.yaml (0600 file permission + masked storage)",
    configuredProviders: "Configured Providers",
    availableProviders: "Available Model Providers",
    configuredTag: "Configured",
    notConfiguredTag: "Not Configured",
    editKey: "Set Key",
    deleteKey: "Clear",
    keyModalTitle: (p: string) => `Configure ${p} API Key`,
    keyModalDesc: "Enter new API Key. Saved directly to .credentials.yaml with 0600 permission.",
    // Accessible name for the input (placeholder "sk-..." is not a label, batch B2)
    keyInputLabel: "API Key",
    keySaved: "API Key updated successfully",
    keyRemoved: "API Key cleared",
    keyClearConfirm: (label: string) => `Clear the API Key for "${label}"?`,
    rawYamlToggle: "Raw YAML Mode",
    keyMasked: "Masked",
    toggleMask: "Show Plaintext",
    hidePlain: "Mask Secrets",
    saveCredentials: "Save Credentials",
    credentialsOverwriteConfirm: "Overwrite .credentials.yaml?",
    credentialsOverwritePoints: [
      "Rewrites the whole file with the editor's current content (not a merge)",
      "The previous file is backed up first as .credentials.yaml.bak-<timestamp>",
      "The write still keeps 0600 permissions and atomic replacement",
    ],
    credentialsSaved: "Credentials saved securely (0600 permission)",
    credentialsSaveFailed: "Failed to save credentials",
    credentialsEmpty: "No credentials configured yet (file empty or not created)",
    insertTemplate: "Insert Template",
    permHint: "Security: Protected with Unix 0600 file mode (read/write by current user only)",
    // DSH 引擎全局设置
    dshSettingsTitle: "DSH Engine Global Configuration",
    dshSettingsSubtitle: "Manage $DSH_HOME/settings.yaml core runtime policies and global defaults",
    dshSettingsSaved: "DSH settings saved successfully",
    dshSettingsSave: "Save Configuration",
    dshSettingsOverwriteConfirm: "Overwrite settings.yaml?",
    dshSettingsOverwritePoints: [
      "Rewrites $DSH_HOME/settings.yaml with the editor's current content (not a merge)",
      "The previous file is backed up first as settings.yaml.bak-<timestamp>",
      "Broken content directly affects dsh startup — refresh and compare before saving",
    ],
    preferencesSection: "Client Preferences",
    localeLabel: "Interface Language",
    localeDesc: "Choose display language for the desktop shell UI; updates immediately",
    localeSystem: "System Default (跟随系统)",
    localeZh: "简体中文 (Chinese Simplified)",
    localeEn: "English (US)",
    guardianSection: "High Availability & Crash Guardian",
    autoRestartLabel: "Auto-Recovery Guardian",
    autoRestartDesc: "Automatically restarts and recovers DSH session upon unexpected process exit. If 3 crashes occur within 60 seconds, circuit-breaker triggers automatically to prevent restart loops.",
    autoRestartEnabled: "Guardian active (with 3 crashes / 60s circuit breaker)",
    autoRestartDisabled: "Guardian disabled (manual retry by default)",
    switcherSection: "Workbench Quick Switcher & Floating Pill",
    floatingSwitcherLabel: "Workbench Floating Pill",
    floatingSwitcherDesc: "Display quick switcher capsule at top-center in DSH workbench (supports mouse drag; shortcuts remain active when disabled)",
    floatingSwitcherEnabled: "Floating pill enabled",
    floatingSwitcherDisabled: "Floating pill hidden (shortcut only)",
    shortcutLabel: "Control Center Shortcut",
    shortcutDesc: "Global hotkey to toggle between DSH Workbench and Control Center",
    shortcutDefault: "Default (⌘ + , / Ctrl + ,)",
    shortcutShiftP: "Command Palette Style (⌘ + ⇧ + P / Ctrl + ⇧ + P)",
    saveSuccess: "Settings saved",
    saveFailed: "Failed to save settings",
    // Saving is disabled when the read fails: settings.json is written as a
    // whole, so writing back without a real baseline would wipe other keys
    // (2026-09-08, see lib/shellSettings.ts)
    settingsLoadFailed:
      "Failed to read preferences — saving is disabled to avoid overwriting other settings",
    retryLoad: "Retry",
    diagnosticsLoadFailed: "Failed to collect diagnostics",
    diagnosticsTitle: "Runtime Environment Health",
    diagnosticsSubtitle: "Real-time runtime telemetry · Resolved paths & storage distribution",
    refreshDiagnostics: "Refresh Telemetry",
    nodeCard: "Node.js Runtime",
    pnpmCard: "pnpm Package Manager",
    dshCard: "DSH Core Engine",
    storageCard: "Storage Distribution",
    statusReady: "Ready",
    statusMissing: "Missing",
    sourceLabel: "Origin",
    pathLabel: "Resolved Path",
    versionLabel: "Version",
    copyReport: "Copy Diagnostics Report",
    reportCopied: "Diagnostics report copied to clipboard",
    profilesUsage: (n: number, size: string) => `${n} Profiles · ${size}`,
    sessionsUsage: (n: number, size: string) => `${n} Sessions · ${size}`,
    totalUsage: (size: string) => `Total Storage: ${size}`,
    logsTitle: "Live Log Viewer",
    logsSubtitle: "Multi-source log aggregation and troubleshooting",
    sourceShell: "DSH Dock Shell Log",
    sourceDsh: "DSH Runtime Log",
    sourceRepair: "Session Repair Log",
    searchPlaceholder: "Filter log messages...",
    autoScroll: "Auto-Scroll",
    copyLogs: "Copy Logs",
    logsCopied: "Logs copied to clipboard",
    clearLogs: "Clear Screen",
    totalLines: (n: number) => `Total ${n} lines`,
    truncatedHint: "Showing latest 500 lines",
    emptyLogs: "No log entries available",
  },
  // Community Plugin Marketplace
  market: {
    clearSearch: "Clear search",
    title: "Plugin Marketplace",
    subtitle: "2700+ community plugins and extensions from awesome-dsh-plugin registry",
    searchPlaceholder: "Search 2700+ plugins by name, description, npm package, or author...",
    allCategories: "All Categories",
    categoryCount: (n: number) => `${n} Categories`,
    totalPlugins: (n: number) => `${n} Plugins`,
    sortStars: "Most Stars",
    sortDownloads: "Most Downloads",
    sortNewest: "Recently Added",
    sortName: "Alphabetical",
    filterInstalled: "Installed Only",
    filterAll: "All Plugins",
    installBtn: "Install",
    distributeBtn: "Distribute",
    installedIn: (count: number) => `Installed in ${count} profiles`,
    notInstalled: "Not Installed",
    installModalTitle: (pkg: string) => `Install Plugin "${pkg}"`,
    installModalDesc: "Choose target profile. It will be added to package.json and built via pnpm automatically.",
    selectProfile: "Select Target Profile",
    installSpecLabel: "Install Source",
    sourceNpm: "NPM Package",
    sourceGithub: "GitHub Repo",
    sourceAutoDetected: "Auto-detected specifier",
    installingBusy: "Installing via pnpm, this may take up to a minute…",
    installSuccess: (pkg: string, prof: string) => `Plugin "${pkg}" successfully installed to profile "${prof}"! Restart the profile to take effect.`,
    installFailed: (msg: string) => `Installation failed: ${msg}`,
    viewReadme: "GitHub",
    viewNpm: "NPM",
    openOfficialDoc: "Home",
    loadingRegistry: "Connecting to community registry & loading 2700+ plugins…",
    loadFailed: "Failed to load marketplace registry",
    retry: "Retry",
    noResults: "No matching plugins found",
    noResultsHint: "Try changing your search query or clearing the category filter",
    paginationPrev: "Previous",
    paginationNext: "Next",
    pageInfo: (current: number, total: number, count: number) => `Page ${current} of ${total} (${count} items)`,
    pageSize: "Per page",
    cacheHit: "Cache Hit",
    refreshRegistry: "Refresh",
    author: "Author",
    addedDate: "Added",
    subtabMarket: "Marketplace",
    subtabInstalled: "Installed",
    expandCategories: (n: number) => `Show All (${n})`,
    collapseCategories: "Show Less",
    manualInstallBtn: "Manual Install",
    manualInstallTitle: "Manual Plugin Installation",
    manualInstallDesc: "Enter an NPM package name, GitHub repository, or Tarball spec, and select the target Profile.",
    manualInstallSpecPlaceholder: "e.g. @deepseek-ai/dsh-pet or github:user/repo",
    manualInstallSubmit: "Install to Selected Profile",
    installQueued: (pkg: string, prof: string) => `Added to download queue: "${pkg}" -> ${prof}`,
    queueTitle: "Downloads",
    queueEmpty: "No download tasks",
    queueClearDone: "Clear finished",
    queueStatusQueued: "Queued",
    queueStatusInstalling: "Installing",
    queueStatusDone: "Installed",
    queueStatusFailed: "Failed",
    queueDismiss: "Dismiss",
    queueRetry: "Retry",
    queueFailedNotice: (pkg: string, detail: string) => `Failed to install "${pkg}": ${detail}`,
  },
  // Shared copy for the destructive-action confirm dialog (2026-09-08, U9)
  confirm: {
    cancel: "Cancel",
  },
}
