// 中文文案常量（i18n 预留；frontend-migration §3.6）。
// STEPS 三元组逐字取自 ui/index.html（第三列 hint 是步骤旁灰色说明，
// 不可丢弃）；headlines 是另一套独立文案（与步骤名不同文），两者不得
// 互相推断。未知错误动作 id 回退展示 id 原文——新宿主/新失败模式无需改组件。
export const t = {
  boot: {
    steps: [
      { no: "01", name: "环境检测", hint: "PATH · 引擎闸 · 平台" },
      { no: "02", name: "准备引擎", hint: "引擎引导（内置 pnpm · node · dsh）" },
      { no: "03", name: "启动工作台", hint: "--port 0" },
      { no: "04", name: "等待就绪", hint: "解析访问地址（慢速冷启动可稍候）" },
      { no: "05", name: "进入工作台", hint: "WebView 导航" },
    ],
    headlines: [
      "检查运行引擎",
      "准备运行环境",
      "启动工作台",
      "等待服务就绪",
      "即将进入工作台",
    ],
    consoleTitle: "启动控制台",
    stRunning: "进行中",
    stError: "异常",
    stReady: "就绪",
    wslOpen: "在 WSL 中打开",
    wslOpenTip: "在 WSL2 发行版内运行 DSH（需 Windows + WSL2）",
    wslFailed: "WSL 切换失败",
    localOpen: "在本机中打开",
    localOpenTip: "切换回本机模式运行 DSH",
    localFailed: "本机切换失败",
    controlCenter: "控制中心",
    controlCenterTip: "打开控制中心面板（管理 Profile / 插件 / 凭据 / 诊断）",
  },
  // 错误动作文案表：boot:error payload 的 actions[] 只给 id，文案在此映射；
  // 组件层以 t.error.actions[id] ?? id 兜底。
  error: {
    fallbackTitle: "启动失败",
    actionFailed: "动作失败",
    actions: {
      retry: "重试",
      upgrade: "升级 DSH 并重试",
      upgrade_only: "后台升级",
      reselect: "返回重选",
    } as Record<string, string>,
  },
  mode: {
    title: "选择运行环境",
    subline: "DSH 可以运行在本机，也可以运行在 WSL2 发行版内——随时可从菜单切换",
    local: "本机运行",
    localDesc: "基于应用内置引擎，首启自动引导 Node 与 DSH；就绪后完全离线运行",
    wsl: "WSL2 内运行",
    wslDesc: "在 WSL2 发行版内运行 DSH（需 Windows + WSL2，发行版内自动铺设引擎）",
    setDefault: "设为默认打开方式（下次自动使用）",
    next: "开始",
    starting: "正在切换…",
    failed: "环境切换失败",
  },
  selector: {
    title: "选择工作台",
    subtitle: "多个 webUi 工作台并存，选择本次启动进入哪一个",
    headline: "进入哪个工作台？",
    subline: "来自你机器上的 DSH 环境 · 选择只影响本次会话",
    pickHint: "官方 Web 工作台开箱即用；其余为你自定义装配的 webUi 工作台。",
    launchingPrefix: "正在启动「",
    launchingSuffix: "」",
    preparingTitle: "正在准备运行引擎",
    preparingSub: "首启自动引导 Node 与 DSH 运行时 · 仅需一次",
    problemHeadline: "启动遇到问题",
    // profile 元数据映射：已知名给正式标题/描述，未知名回退 CUSTOM 形态
    items: {
      web: { title: "官方 Web 工作台", desc: "DSH 官方维护的 Web 界面", tag: "DEFAULT" },
    } as Record<string, { title: string; desc: string; tag: string }>,
    customDesc: "自定义装配的 webUi 工作台",
    customTag: "CUSTOM",
    // 顶栏版本芯片短文案
    chipDshNew: "有新版",
    chipDshOk: "已是最新",
    chipDetecting: "检测中",
    chipCheckFailed: "检测失败",
    chipClientNew: "客户端有新版",
    chipClientUpdating: "客户端更新",
    chipClientUpdatingRun: "客户端更新中…",
  },
  updateBanner: {
    // 升级提示条（ADR-0010 升级呈现；非阻断、可忽略同版本）
    dshTitle: "dsh 有新版本 v{latest}（当前 v{current}）",
    dshConsequence: "升级可获得安全修复与改进；长期不升级可能导致未来版本门槛抬升后无法直接追新。",
    clientTitle: "桌面客户端有新版本 v{latest}",
    clientConsequence: "建议升级以获得问题修复与体验改进。",
    dismissTip: "忽略此版本（不再提醒）",
    entryHint: "可从菜单 / 托盘的「关于」进入更新中心。",
  },
  about: {
    title: "关于与更新",
    tagline: "更新中心 · 桌面客户端与运行环境",
    // 客户端状态机文案（键 = UpdatePhase，failed/done 附带数据的行在组件内插值）
    clientLabel: "桌面客户端",
    phases: {
      idle: "待定",
      checking: "检测中",
      available: "可用",
      upToDate: "最新",
      downloading: "下载中",
      installing: "安装中",
      relaunching: "重启中",
      done: "完成",
      failed: "失败",
    },
    lines: {
      idle: "点击「检查更新」查询官方发布源",
      checking: "正在检查官方更新源",
      upToDate: "已是最新",
      downloading: "正在下载新版本",
      installing: "正在安装新版本",
      relaunching: "即将重启进入新版本",
      failedTitle: "更新失败",
    },
    foundNew: "发现新版",
    releaseNotes: "发布说明",
    downloadBtn: "下载并安装",
    preparing: "准备安装…",
    checkBtn: "检查更新",
    updatedDone: "已更新到",
    restartNote: "客户端更新由官方 Releases 签名分发，安装后自动重启。",
    // 运行环境两维度
    envTitle: "运行环境",
    dshLabel: "DSH",
    nodeLabel: "Node 运行时",
    notDetected: "未检出",
    detecting: "检测中…",
    hasNew: "有新版",
    latestIsNewest: "已是最新",
    latestOfficial: "官方最新",
    notYetLocal: "本地尚未检出",
    checkFailedNet: "DSH 检测失败（网络不可达）",
    nodeFromEngine: "壳引擎 · 随应用内置管理",
    nodeFromSystem: "来自你的系统",
    nodeManaged: "应用托管 · 随启动自动准备",
    nodeUnknown: "尚未确定",
    dshUpgradeNote: "升级 DSH 只动 pnpm/npm 全局包，不触碰你的数据与配置。",
    upgrading: "升级中…",
    upgradeFailed: "升级失败",
    upgradeRunning: "正在全局安装（pnpm/npm），可能需要数分钟…",
    btnCheck: "检查",
    btnUpgrade: "升级",
    // 工作台入口
    openInBrowser: "在浏览器中打开",
    workbenchNotReady: "工作台尚未就绪",
    liveSessionActive: "工作台实例就绪",
    copyDiagnostics: "复制诊断信息",
    diagnosticsCopied: "诊断信息已复制到剪贴板",
    officialChannel: "官方发布通道",
  },
  // 控制中心（4.3 前端刀）。
  profiles: {
    title: "控制中心",
    subtitle: "多工作台管理、插件生态矩阵、会话自愈维护与系统控制台",
    refresh: "刷新",
    refreshing: "刷新中…",
    switchToDsh: "返回工作台",
    switchToDshTip: "快速切换至 DSH 主工作台（快捷键：⌘ + , / Ctrl + , 双向切换）",
    createBtn: "新建工作台",
    loadFailed: "profile 列表读取失败——请确认 dsh 环境后重试",
    retryLoad: "重试",
    // 列表行
    tagMaterialized: "已创建",
    tagTemplate: "可首启",
    tagNoUi: "无界面",
    templateHint: "内置模板 · 首次启动自动创建",
    defaultBadge: "默认启动",
    runningBadge: "运行中",
    setDefault: "设为默认启动",
    defaultIs: "当前默认",
    launch: "启动",
    launchWorking: "启动中…",
    metaBundles: (n: number) => `${n} 个插件`,
    metaDeps: (n: number) => (n > 0 ? `${n} 项依赖` : "无额外依赖"),
    metaSep: "·",
    // 详情
    detailTitle: (name: string) => `「${name}」详情`,
    detailPackage: "清单名",
    detailBundles: "插件组合（dsh.profile.bundles）",
    detailDeps: "外挂插件（dependencies）",
    detailPatch: "cordis.patch.yml 原文",
    detailPatchNone: "尚无 patch 层（首次启动时由 dsh 生成）",
    detailEmptyDeps: "无额外依赖",
    detailClose: "关闭",
    // 插件清单（4.4①）：静态清单 + 运行态快照（复现点 11）
    pluginNotInstalled: "未安装",
    // 插件安装/卸载/更新（4.4②）：dsh plugin 转发链
    pluginInstallBtn: "安装插件",
    pluginInstallPlaceholder: "包名 或 包名@版本（如 dsh-xxx@^1.2）",
    pluginInstallSubmit: "安装",
    pluginInstallCancel: "取消",
    pluginInstallBusy: "安装中…（需要下载，可能数十秒到数分钟）",
    pluginUninstall: "卸载",
    pluginUpdate: "更新",
    pluginDisable: "禁用（重启后生效）",
    pluginEnable: "启用（重启后生效）",
    pluginDisabled: "已禁用",
    pluginOpBusyRemove: "卸载中…",
    pluginOpBusyUpdate: "更新中…",
    // 更新检查（4.4④）：registry dist-tags 口径 + 版本选择
    checkUpdatesBtn: "检查更新",
    checkingBtn: "查询中…",
    updateChecked: (r: { checked: number; failed: number }) =>
      `已查 ${r.checked} 个插件${r.failed ? ` · ${r.failed} 个查询失败` : ""}`,
    allUpToDate: "全部最新",
    updateHint: "选择版本更新",
    pickVersionTitle: (pkg: string) => `「${pkg}」可选版本`,
    versionLatest: "最新",
    versionCurrent: "当前",
    versionsLoadFailed: "版本列表查询失败",
    hiddenLayersHint: (n: number) => `另有 ${n} 个外挂插件层，见下方外挂插件清单`,
    pluginWithDsh: "版本随 dsh",
    runtimeSummary: (s: { active: number; failed: number; loading: number; disabled: number }) =>
      `会话运行中 · ${s.active} 行运行中${s.failed ? ` · ${s.failed} 行失败` : ""}${s.loading ? ` · ${s.loading} 行加载中` : ""}${s.disabled ? ` · ${s.disabled} 行停用` : ""}`,
    runtimeUnavailable: "该 profile 当前未运行，仅显示静态清单",
    // 创建
    createTitle: "新建 Profile",
    createNameLabel: "Profile 名字",
    createNamePlaceholder: "如 my-workbench",
    createNameHelp: "同一名字再次创建即重试安装（幂等）；已完整存在的名字会被拒绝",
    createTemplateHint: (name: string) =>
      `「${name}」是内置模板：将以官方模板初始化（${name} = 基础 + ${name === "web" ? "Web" : "Headless"} 工作台）`,
    createDefaultHint: "将创建基础 + Web 工作台（与出厂 web 模板同构、零下载），可设为默认启动",
    createSubmit: "创建",
    createBusy: "创建中…（本地初始化，通常秒级完成）",
    createDoneReady: "创建完成：基础 + Web 工作台就绪，可立即启动或设为默认",
    createDonePending: "已创建，但插件安装未完成——可稍后重试创建（幂等）",
    createDoneFailed: "创建未完成",
    createAgain: "再试一次",
    // 复制 / 重命名
    copyTitle: (name: string) => `复制「${name}」`,
    renameTitle: (name: string) => `重命名「${name}」`,
    newNameLabel: "新名字",
    copyNote: "复制会排除 node_modules（新目录由 pnpm 重新安装），其余文件逐字照搬",
    renameNote: "重命名后 node_modules 将被清理，dsh 下次启动自动重装",
    submitCopy: "创建副本",
    submitRename: "确认重命名",
    actionRename: "重命名",
    actionDelete: "删除",
    busyShort: "处理中…",
    renameSame: "新名字与当前名字相同",
    nameOccupied: "该名字已被占用",
    renameDone: (name: string) => `已重命名为「${name}」`,
    copyDone: (name: string) => `已创建副本「${name}」`,
    warningsLabel: "需要人工检查",
    opFailed: "操作失败",
    // 删除确认（要素按 ADR-0009 §2/§4 要求逐条列明）
    deleteTitle: (name: string) => `删除「${name}」？`,
    deleteNote: "此操作不可撤销",
    deletePoint: [
      "只删除该 profile 目录，不会删除会话、凭据等全局数据",
      "确保没有其他 dsh 实例（含终端自启）正在使用该 profile",
      "若它是内置模板名（web/headless），删除后首次使用将重新物化",
    ] as readonly string[],
    deleteConfirm: (name: string) => `确认删除 ${name}`,
    deleteBusy: "删除中…",
    deleteDoneCleared: "已删除；它曾是默认启动 profile，已回退为 web",
    deleteDone: "已删除",
    // 设默认
    setDefaultDone: (name: string) => `已设「${name}」为默认启动 profile`,
    // 切换（4.3⑥）：停当前会话以目标 profile 重启；不写默认，失败可重试
    switchTitle: (name: string) => `切换到「${name}」？`,
    switchNote: "将停止当前 dsh 并以该 profile 重启，进行中的任务会中断（会话历史已落盘，不受影响）；默认启动设置不变。",
    switchFrom: (active: string) => `当前运行：「${active}」`,
    switchConfirm: (name: string) => `切换到「${name}」`,
    switchBusy: "切换中…",
    switchDone: (name: string) => `已开始切换到「${name}」，进度见主窗口`,
    // 重启（4.4③）：同 profile 走切换链；恒弹确认（必杀运行中会话）
    restart: "重启",
    restartTitle: (name: string) => `重启「${name}」？`,
    restartNote: "将停止当前 dsh 并以同一 profile 重新启动，进行中的任务会中断（会话历史已落盘，不受影响）；刚安装/卸载/禁用的插件借此生效。",
    restartConfirm: (name: string) => `重启「${name}」`,
    restartBusy: "正在重启…",
    restartDone: (name: string) => `已触发「${name}」重启，进度见主窗口`,
    // 视图切换（4.4④ 收口）：管理器页内视图
    viewProfiles: "Profile 列表",
    viewPluginHub: "插件中心",
    viewPlugins: "已安装插件",
    viewMarket: "插件市场",
    viewSessions: "会话维护",
    viewConsole: "系统控制台",
    overviewSubtitle: "全部 profile 的第三方插件分布",
    overviewSourceCount: (n: number) => `${n} 个 profile`,
    overviewEmpty: "各 profile 还没有安装第三方插件",
    overviewEmptyHint: "在任一 profile 的详情里安装后，这里会自动汇总",
    overviewNotInstalled: "未安装",
    // 从其他 profile 安装（4.4④）：多选批量 + 可选连配置（写入例外 #4）
    importBtn: "从其他导入",
    importBtnTitle: "把其他 profile 已安装的插件装到这里",
    importTitle: (name: string) => `从其他 profile 安装到「${name}」`,
    importNote: "默认安装来源同版本；「连配置」会把来源 profile 里该插件的配置行原样复制过来（目标已有配置时不覆盖）",
    importLoading: "正在扫描其他 profile…",
    importEmpty: "其他 profile 还没有已安装的第三方插件",
    importRowsFailedNote: "部分行表查询失败，「连配置」可用性可能不准",
    importConfig: "连配置",
    importNoConfig: "无配置可带",
    importSelected: (n: number) => `已选 ${n} 项`,
    importStart: (n: number) => `安装 ${n} 项`,
    importRunning: (i: number, total: number) => `正在安装 ${i}/${total}`,
    importDone: (ok: number, fail: number) =>
      `从其他 profile 安装完成：${ok} 成功${fail ? ` · ${fail} 失败` : ""}`,
    importDoneBtn: "完成",
    importFailures: "失败明细",
    // 扩展文案（Master-Detail 工作台与交互升级）
    searchPlaceholder: "搜索 Profile...",
    searchPluginsPlaceholder: "搜索已装插件...",
    searchAllPluginsPlaceholder: "搜索全域插件名称、描述或 Profile...",
    tabPlugins: "外挂插件",
    tabBundles: "底座组合",
    tabPatch: "Patch YAML",
    tabMcp: "MCP 扩展",
    mcpTitle: "MCP 服务器管理器",
    mcpSubtitle: "管理当前 Profile 的 Model Context Protocol 工具与外部服务扩展",
    mcpEmpty: "当前 Profile 尚未配置任何 MCP 服务",
    mcpAddBtn: "添加 MCP 服务",
    mcpEditBtn: "编辑",
    mcpDeleteBtn: "删除",
    mcpDeleteConfirm: (name: string) => `确定移除 MCP 服务「${name}」？\n\n将从当前 Profile 的 cordis.patch.yml 中安全删除。`,
    mcpActiveTools: (count: number) => `运行时已加载 ${count} 个工具`,
    mcpNoActiveTools: "当前未在运行态或无导出工具",
    mcpModalTitle: "配置 MCP 服务",
    mcpModalDesc: "配置服务名称、运行命令、参数与环境变量，保存后将整体安全更新至 cordis.patch.yml。",
    mcpPresetTitle: "快速应用常用预设",
    mcpServerName: "服务标识 (Server Name)",
    mcpCommand: "启动命令 (Command)",
    mcpArgs: "命令参数 (Args)",
    mcpEnv: "环境变量 (ENV, KEY=VALUE 每行一个)",
    mcpPrefix: "工具前缀",
    mcpSaveBtn: "保存服务",
    mcpSaveSuccess: (name: string) => `MCP 服务「${name}」已成功保存至 cordis.patch.yml`,
    mcpDeleteSuccess: "MCP 服务已成功删除",
    mcpConfigSaved: "MCP 配置已同步至 cordis.patch.yml",
    emptySelectTitle: "未选定 Profile",
    emptySelectSubtitle: "在左侧选择一个 Profile 或新建工作台，即可在此配置插件、查看底座与管理 YAML Patch。",
    quickDistribute: "分发到...",
    distributeTitle: (pkg: string) => `将「${pkg}」分发安装到其他 Profile`,
    distributeNote: "选择目标 Profile，将以相同版本执行安装并可连带迁移配置",
    distributeDone: (pkg: string, target: string) => `已成功将「${pkg}」安装至「${target}」`,
    copyPatchSuccess: "Patch YAML 内容已复制到剪贴板",
    rawYamlHint: "此为 dsh 生成的 cordis.patch.yml 权威底层配置（只读查看与诊断）",
    filterAll: "全部",
    filterMaterialized: "已创建",
    filterTemplates: "模板",
  },
  sessions: {
    title: "会话维护与自愈",
    subtitle: "检测、诊断与自愈修复 DSH 会话日志异常（如序列号断裂、交叉并发落盘等）",
    scanBtn: "刷新扫描",
    repairAllBtn: "一键全量体检与自愈",
    repairing: "正在自愈修复中…",
    searchPlaceholder: "搜索会话 ID 或项目名...",
    filterAll: "全部会话",
    filterNeedsRepair: "仅看异常",
    groupByProject: "按项目分组",
    allProjects: "全部项目",
    workspacePath: "工作区路径",
    openInFinder: "在文件管理器中打开",
    totalCount: (n: number) => `共发现 ${n} 个会话`,
    healthyCount: (n: number) => `${n} 个健康`,
    needsRepairCount: (n: number) => `${n} 个需修复`,
    repairBtn: "一键修复",
    backupTag: "已备份",
    compressedTag: "Zstd 压缩",
    plainTag: "Plaintext",
    repairSuccess: (id: string) => `会话「${id}」自愈修复完成`,
    repairAllSuccess: "全量会话扫描与自愈完成！",
    emptyList: "暂未发现会话记录",
    emptyFilter: "没有匹配的会话",
    lastUpdated: "最后活跃",
    fileSize: "体积",
    path: "存储路径",
    deleteBtn: "删除",
    deleteConfirmTitle: (id: string) => `确定删除会话「${id}」？`,
    deleteConfirmNote: "此操作将永久删除该会话记录文件及其本地历史，不可撤销。",
    deleteSuccess: "会话记录已成功删除",
    copyPath: "复制路径",
    pathCopied: "会话路径已复制",
  },
  console: {
    title: "系统控制台与诊断",
    subtitle: "偏好设置、模型凭据、DSH 引擎配置、崩溃自动守护、健康大盘与实时日志",
    tabPreferences: "偏好与守护",
    tabCredentials: "模型凭据",
    tabDshSettings: "DSH 引擎配置",
    tabDiagnostics: "健康大盘",
    tabLogs: "运行日志",
    // 凭据安全管理（4.5）
    credentialsTitle: "大模型与服务凭据",
    credentialsSubtitle: "安全管理 $DSH_HOME/.credentials.yaml（严格 0600 权限 + 脱敏存储）",
    configuredProviders: "已配置提供商",
    availableProviders: "可用模型提供商",
    configuredTag: "已配置",
    notConfiguredTag: "未配置",
    editKey: "配置 Key",
    deleteKey: "清除",
    keyModalTitle: (p: string) => `配置 ${p} API Key`,
    keyModalDesc: "请输入新的 API Key。保存后将写入 .credentials.yaml 并严格维持 0600 权限。",
    keySaved: "API Key 已成功更新",
    keyRemoved: "API Key 已清除",
    rawYamlToggle: "切换 YAML 原文模式",
    keyMasked: "已脱敏显示",
    toggleMask: "显示明文",
    hidePlain: "脱敏隐藏",
    saveCredentials: "保存凭据配置",
    credentialsSaved: "凭据文件已安全保存（权限 0600）",
    credentialsSaveFailed: "保存凭据失败",
    credentialsEmpty: "当前尚未配置任何凭据（文件未创建或为空）",
    insertTemplate: "快速插入模板",
    permHint: "权限保障：此文件受 Unix 0600 文件级安全保护，仅本机当前用户可读写",
    // DSH 引擎全局设置
    dshSettingsTitle: "DSH 引擎全局配置",
    dshSettingsSubtitle: "管理 $DSH_HOME/settings.yaml 权威核心运行策略与全局默认参数",
    dshSettingsSaved: "DSH 设置已成功保存",
    // 偏好与语言
    preferencesSection: "客户端偏好",
    localeLabel: "界面语言",
    localeDesc: "选择桌面壳界面的显示语言；更改后立即生效",
    localeSystem: "跟随系统语言 (System Default)",
    localeZh: "简体中文 (Chinese Simplified)",
    localeEn: "English (US)",
    // 崩溃守护
    guardianSection: "高可用与崩溃守护",
    autoRestartLabel: "崩溃自动恢复守护",
    autoRestartDesc: "当检测到 DSH 会话进程意外退出时，后台自动拉起恢复；60 秒内若连续崩溃达到 3 次将自动触发熔断保护，停止重试并弹出诊断错误卡。",
    autoRestartEnabled: "已开启守护（含 3次/60s 熔断保护）",
    autoRestartDisabled: "未开启（默认手动重试）",
    // 悬浮胶囊与快捷键
    switcherSection: "工作台快速切换与胶囊挂件",
    floatingSwitcherLabel: "工作台悬浮胶囊",
    floatingSwitcherDesc: "在 DSH 工作台顶部居中显示控制中心入口胶囊（支持鼠标自由拖拽移动；关闭后依然可通过快捷键呼出）",
    floatingSwitcherEnabled: "已开启悬浮胶囊",
    floatingSwitcherDisabled: "已关闭（仅使用快捷键）",
    shortcutLabel: "控制中心呼出快捷键",
    shortcutDesc: "在 DSH 主工作台与控制中心之间切换的全局快捷键",
    shortcutDefault: "默认快捷键（⌘ + , / Ctrl + ,）",
    shortcutShiftP: "命令面板风格（⌘ + ⇧ + P / Ctrl + ⇧ + P）",
    saveSuccess: "设置已保存",
    saveFailed: "设置保存失败",
    // 诊断大盘
    diagnosticsTitle: "运行环境诊断大盘",
    diagnosticsSubtitle: "环境健康实时采集 · 真实解析路径与存储分布",
    refreshDiagnostics: "刷新体检",
    nodeCard: "Node.js 运行时",
    pnpmCard: "pnpm 全局包管理",
    dshCard: "DSH 核心引擎",
    storageCard: "存储空间分布",
    statusReady: "就绪",
    statusMissing: "未检出",
    sourceLabel: "来源",
    pathLabel: "解析路径",
    versionLabel: "版本",
    copyReport: "复制完整诊断报告",
    reportCopied: "诊断报告已复制到剪贴板",
    profilesUsage: (n: number, size: string) => `${n} 个 Profile · 占用 ${size}`,
    sessionsUsage: (n: number, size: string) => `${n} 个会话 · 占用 ${size}`,
    totalUsage: (size: string) => `总存储占用：${size}`,
    // 日志查看器
    logsTitle: "实时日志查看器",
    logsSubtitle: "多源日志聚合分析与排障",
    sourceShell: "DSH Dock 壳日志",
    sourceDsh: "DSH 运行时日志",
    sourceRepair: "会话自愈日志",
    searchPlaceholder: "过滤日志关键字...",
    autoScroll: "自动滚底",
    copyLogs: "复制全部日志",
    logsCopied: "日志已复制到剪贴板",
    clearLogs: "清屏",
    totalLines: (n: number) => `共 ${n} 行`,
    truncatedHint: "已截取最新 500 行日志",
    emptyLogs: "暂无日志内容",
  },
  // 插件市场 (awesome-dsh-plugin 社区 Registry)
  market: {
    title: "社区插件市场",
    subtitle: "基于 awesome-dsh-plugin 官方聚合的 2700+ 社区插件与扩展生态",
    searchPlaceholder: "搜索 2700+ 插件名称、功能描述、NPM 包名或作者...",
    allCategories: "全部分类",
    categoryCount: (n: number) => `${n} 个分类`,
    totalPlugins: (n: number) => `${n} 款插件`,
    sortStars: "最多星标",
    sortDownloads: "最高下载",
    sortNewest: "最新上架",
    sortName: "名称排序",
    filterInstalled: "仅看已装",
    filterAll: "全部插件",
    installBtn: "安装",
    distributeBtn: "分发",
    installedIn: (count: number) => `已装于 ${count} 个 Profile`,
    notInstalled: "未安装",
    installModalTitle: (pkg: string) => `安装插件「${pkg}」`,
    installModalDesc: "选择要安装的目标 Profile。安装后将自动写入该 Profile 的 package.json 并通过 pnpm 自动构建安装。",
    selectProfile: "选择目标 Profile",
    installSpecLabel: "安装源",
    sourceNpm: "NPM 官方包",
    sourceGithub: "GitHub 仓库",
    sourceAutoDetected: "已自动识别规范",
    installingBusy: "正在通过 pnpm 安装插件，可能需要几十秒…",
    installSuccess: (pkg: string, prof: string) => `插件「${pkg}」已成功安装至 Profile「${prof}」！重启该 Profile 后生效。`,
    installFailed: (msg: string) => `安装失败：${msg}`,
    viewReadme: "GitHub",
    viewNpm: "NPM",
    openOfficialDoc: "主页",
    copyCmd: "复制命令",
    copied: "已复制",
    loadingRegistry: "正在连接社区 Registry 加载 2700+ 插件目录…",
    loadFailed: "加载插件市场目录失败",
    retry: "重新加载",
    noResults: "未找到符合条件的插件",
    noResultsHint: "尝试更换搜索词或清除分类筛选条件",
    paginationPrev: "上一页",
    paginationNext: "下一页",
    pageInfo: (current: number, total: number, count: number) => `第 ${current} / ${total} 页（共 ${count} 款）`,
    pageSize: "每页",
    cacheHit: "本地缓存命中",
    refreshRegistry: "刷新市场",
    author: "作者",
    addedDate: "上架时间",
    subtabMarket: "插件市场",
    subtabInstalled: "已安装",
    expandCategories: (n: number) => `展开全部 (${n})`,
    collapseCategories: "收起分类",
  },
} as const

type RecursiveString<T> = {
  [K in keyof T]: T[K] extends (...args: infer A) => unknown
    ? (...args: A) => string
    : T[K] extends readonly (infer E)[]
      ? E extends object
        ? readonly RecursiveString<E>[]
        : readonly string[]
      : T[K] extends object
        ? RecursiveString<T[K]>
        : string
}

export type AppCopy = RecursiveString<typeof t>
